server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jingxuan_db?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: app_user
    password: Secure@123

    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1800000
      pool-name: HikariCP
    task:
      execution:
        pool:
          core-size: 32
          max-size: 64
          queue-capacity: 100
          keep-alive: 60s

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.mutithreadservice.model
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.example.mutithreadservice: DEBUG
    org.mybatis: DEBUG



